// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo8oEM6zwIGzKGPYUB90fvCE9B2dMvt0o',
    appId: '1:18009762578:web:0abb971a9a6828bec5a1cb',
    messagingSenderId: '18009762578',
    projectId: 'dashboard-dt-af6c3',
    authDomain: 'dashboard-dt-af6c3.firebaseapp.com',
    storageBucket: 'dashboard-dt-af6c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb3MWIOCh_vBjLmyfTUxSLempuL32XeBs',
    appId: '1:18009762578:android:050b1b11fee9345dc5a1cb',
    messagingSenderId: '18009762578',
    projectId: 'dashboard-dt-af6c3',
    storageBucket: 'dashboard-dt-af6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtughDJQVIlqUqMpeOxgP7Qka22t_zQk',
    appId: '1:18009762578:ios:6c4c70c8f8859ed3c5a1cb',
    messagingSenderId: '18009762578',
    projectId: 'dashboard-dt-af6c3',
    storageBucket: 'dashboard-dt-af6c3.firebasestorage.app',
    iosBundleId: 'com.example.digitalTwinControlCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtughDJQVIlqUqMpeOxgP7Qka22t_zQk',
    appId: '1:18009762578:ios:6c4c70c8f8859ed3c5a1cb',
    messagingSenderId: '18009762578',
    projectId: 'dashboard-dt-af6c3',
    storageBucket: 'dashboard-dt-af6c3.firebasestorage.app',
    iosBundleId: 'com.example.digitalTwinControlCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo8oEM6zwIGzKGPYUB90fvCE9B2dMvt0o',
    appId: '1:18009762578:web:382f7a9ccce15218c5a1cb',
    messagingSenderId: '18009762578',
    projectId: 'dashboard-dt-af6c3',
    authDomain: 'dashboard-dt-af6c3.firebaseapp.com',
    storageBucket: 'dashboard-dt-af6c3.firebasestorage.app',
  );
}
